import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.REACT_APP_GEMINI_API_KEY);

async function askGemini(prompt) {
  const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
  const result = await model.generateContent(prompt);
  return result.response.text();
}

async function fetchPRFiles(prNumber) {
  const BASE_URL = `https://api.github.com/repos/${process.env.REACT_APP_GITHUB_USERNAME}/${process.env.REACT_APP_GITHUB_REPO}`;
  const headers = {
    Authorization: `Bearer ${process.env.REACT_APP_GITHUB_TOKEN}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
  };

  try {
    const [prRes, filesRes] = await Promise.all([
      fetch(`${BASE_URL}/pulls/${prNumber}`, { headers }),
      fetch(`${BASE_URL}/pulls/${prNumber}/files`, { headers })
    ]);

    const pr = await prRes.json();
    const files = await filesRes.json();

    return { pr, files };
  } catch (err) {
    throw new Error(`GitHub fetch failed: ${err.message}`);
  }
}

export async function runCodeReviewAgent(userMessage, onUpdate) {

  // Extract PR number
  const prExtract = await askGemini(`
    Extract ONLY the PR number from this message.
    Respond with just the number, nothing else.
    Message: "${userMessage}"
  `);
  const prNumber = prExtract.trim().replace(/\D/g, '');

  if (!prNumber) {
    return "❌ Please specify a PR number. Example: 'Review PR #1'";
  }

  // ── AGENT 1: Fetcher Agent ───────────────────────────────────────────────
  onUpdate(`📥 Fetcher Agent loading PR #${prNumber}...`);

  let prData;
  try {
    prData = await fetchPRFiles(prNumber);
  } catch (err) {
    return `❌ PR #${prNumber} not found. Make sure the PR exists in your repo and try again.`;
  }
  const { pr, files } = prData;

  const filesSummary = files.map(f =>
    `File: ${f.filename}\nChanges: +${f.additions} -${f.deletions}\nPatch:\n${f.patch?.slice(0, 500) || 'No patch available'}`
  ).join('\n\n---\n\n');

  // ── AGENT 2: Reviewer Agent ──────────────────────────────────────────────
  onUpdate("🔍 Reviewer Agent analyzing the code...");

  const review = await askGemini(`
    You are a senior software engineer doing a thorough code review.
    
    PR Title: ${pr.title}
    Author: ${pr.user?.login}
    Branch: ${pr.head?.ref} → ${pr.base?.ref}
    Files changed: ${files.length}
    
    Code changes:
    ${filesSummary}
    
    Please review and identify:
    1. Potential bugs or issues
    2. Security concerns
    3. Performance issues
    4. Code quality and best practices
    5. What's done well
    
    Be specific with line references where possible.
  `);

  // ── AGENT 3: Reporter Agent ──────────────────────────────────────────────
  onUpdate("📝 Reporter Agent writing review summary...");

  const summary = await askGemini(`
    Based on this code review, write a concise executive summary 
    with a clear APPROVE / REQUEST CHANGES / NEEDS DISCUSSION recommendation.
    
    Review findings: ${review}
    
    Format:
    RECOMMENDATION: [APPROVE / REQUEST CHANGES / NEEDS DISCUSSION]
    SUMMARY: [2-3 sentences]
    TOP 3 ACTIONS: [numbered list]
  `);

  // ── FINAL REPORT ─────────────────────────────────────────────────────────
  return `## 👨‍💻 Code Review: PR #${prNumber}

**Title:** ${pr.title}
**Author:** ${pr.user?.login}
**Branch:** ${pr.head?.ref} → ${pr.base?.ref}
**Files Changed:** ${files.length}

### 📋 Executive Summary
${summary}

### 🔍 Detailed Review
${review}

---
*Generated by Code Review Agent Team: Fetcher → Reviewer → Reporter*`;
}