import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.REACT_APP_GEMINI_API_KEY);

async function askGemini(prompt) {
  const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
  const result = await model.generateContent(prompt);
  return result.response.text();
}

async function searchWeb(query) {
  try {
    const res = await fetch(
      `https://api.duckduckgo.com/?q=${encodeURIComponent(query)}&format=json&no_html=1&skip_disambig=1`
    );
    const data = await res.json();
    return (
      data.AbstractText ||
      data.Answer ||
      data.RelatedTopics?.[0]?.Text ||
      `No result found for: ${query}`
    );
  } catch {
    return `Search failed for: ${query}`;
  }
}

export async function runSalesAgent(userMessage, onUpdate) {

  // ── AGENT 1: Research Agent ──────────────────────────────────────────────
  onUpdate("🔍 Research Agent searching for company info...");

  // Extract company name from message
  const companyExtract = await askGemini(`
    Extract ONLY the company name from this message. 
    Respond with the company name only, nothing else.
    Message: "${userMessage}"
  `);
  const company = companyExtract.trim();

  // Search for company info
  const [companyInfo, newsInfo, competitorInfo] = await Promise.all([
    searchWeb(`${company} company overview revenue industry`),
    searchWeb(`${company} latest news 2025`),
    searchWeb(`${company} competitors market`)
  ]);

  onUpdate("📊 Scorer Agent evaluating the lead...");

  // ── AGENT 2: Scorer Agent ────────────────────────────────────────────────
  const scoreResult = await askGemini(`
    You are a B2B sales lead scorer. Based on this information about ${company}, 
    score them as a sales lead from 1-10 and explain why in 2-3 sentences.
    
    Company Info: ${companyInfo}
    Recent News: ${newsInfo}
    Market Position: ${competitorInfo}
    
    Respond in this exact format:
    SCORE: [number]/10
    REASON: [2-3 sentence explanation]
    BEST_ANGLE: [One sentence on the best sales angle to use]
  `);

  onUpdate("✍️ Writer Agent drafting outreach email...");

  // ── AGENT 3: Writer Agent ────────────────────────────────────────────────
  const email = await askGemini(`
    You are an expert B2B sales copywriter. Write a short, personalized 
    cold outreach email to ${company} based on this research.
    
    Company Info: ${companyInfo}
    News: ${newsInfo}
    Score Info: ${scoreResult}
    
    Rules:
    - Subject line that gets opened
    - 3-4 short paragraphs max
    - Personal and specific, not generic
    - Clear call to action
    - Professional but friendly tone
    
    Format:
    SUBJECT: [subject line]
    
    [email body]
  `);

  // ── FINAL REPORT ─────────────────────────────────────────────────────────
  return `## 💼 Sales Analysis: ${company}

### 📊 Lead Score
${scoreResult}

### 🔍 Research Summary
**Company:** ${companyInfo.slice(0, 300)}...

**Latest News:** ${newsInfo.slice(0, 200)}...

### 📧 Outreach Email
\`\`\`
${email}
\`\`\`

---
*Generated by Sales Agent Team: Research → Scorer → Writer*`;
}